//UI
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';
export const SHOW_SLIDER = 'SHOW_SLIDER';
export const HIDE_SLIDER = 'HIDE_SLIDER';
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const SHOW_RIGHT_SIDEBAR = 'SHOW_RIGHT_SIDEBAR';
export const HIDE_RIGHT_SIDEBAR = 'HIDE_RIGHT_SIDEBAR';

//Auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_MOBILE = 'AUTH_MOBILE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const INIT_URL = 'INIT_URL';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

//News Feed
export const SET_SWAGGER_FEED = 'SET_SWAGGER_FEED';
export const UPDATE_SWAGGER_FEED = 'UPDATE_SWAGGER_FEED';
export const UPDATE_SWAGGER_FEED_COMMENT = 'UPDATE_SWAGGER_FEED_COMMENT';
export const UPDATE_SWAGGER_FEED_COMMENT_LIKE = 'UPDATE_SWAGGER_FEED_COMMENT_LIKE';
export const UPDATE_SWAGGER_FEED_TEXT = 'UPDATE_SWAGGER_FEED_TEXT';
export const UPDATE_SWAGGER_FEED_DELETE = 'UPDATE_SWAGGER_FEED_DELETE';
export const UPDATE_SWAGGER_FEED_COMMENT_REPLY = 'UPDATE_SWAGGER_FEED_COMMENT_REPLY';
export const CLEAR_SWAGGER_FEED = 'CLEAR_SWAGGER_FEED';
export const SET_HASH_FEED = 'SET_HASH_FEED';
export const UPDATE_HASH_FEED = 'UPDATE_HASH_FEED';
export const UPDATE_HASH_FEED_COMMENT = 'UPDATE_HASH_FEED_COMMENT';
export const UPDATE_HASH_FEED_COMMENT_LIKE = 'UPDATE_HASH_FEED_COMMENT_LIKE';
export const UPDATE_HASH_FEED_TEXT = 'UPDATE_HASH_FEED_TEXT';
export const UPDATE_HASH_FEED_DELETE = 'UPDATE_HASH_FEED_DELETE';
export const UPDATE_HASH_FEED_COMMENT_REPLY = 'UPDATE_HASH_FEED_COMMENT_REPLY';
export const CLEAR_HASH_FEED = 'CLEAR_HASH_FEED';
export const SET_TALENT_FEED = 'SET_TALENT_FEED';
export const UPDATE_TALENT_FEED = 'UPDATE_TALENT_FEED';
export const UPDATE_TALENT_FEED_COMMENT = 'UPDATE_TALENT_FEED_COMMENT';
export const UPDATE_TALENT_FEED_COMMENT_LIKE = 'UPDATE_TALENT_FEED_COMMENT_LIKE';
export const UPDATE_TALENT_FEED_TEXT = 'UPDATE_TALENT_FEED_TEXT';
export const UPDATE_TALENT_FEED_DELETE = 'UPDATE_TALENT_FEED_DELETE';
export const UPDATE_TALENT_FEED_COMMENT_REPLY = 'UPDATE_TALENT_FEED_COMMENT_REPLY';
export const CLEAR_TALENT_FEED = 'CLEAR_TALENT_FEED';
export const UPDATE_PROFILE_FEED_TEXT = 'UPDATE_PROFILE_FEED_TEXT';
export const UPDATE_PROFILE_FEED_DELETE = 'UPDATE_PROFILE_FEED_DELETE';
export const SET_PROFILE_IMAGES = 'SET_PROFILE_IMAGES';
export const UPDATE_SWAGGER_COMMENT_MANIPULATE = 'UPDATE_SWAGGER_COMMENT_MANIPULATE';
export const UPDATE_HASH_COMMENT_MANIPULATE = 'UPDATE_HASH_COMMENT_MANIPULATE';
export const UPDATE_TALENT_COMMENT_MANIPULATE = 'UPDATE_TALENT_COMMENT_MANIPULATE';
export const UPDATE_SWAGGER_FOLLOW = 'UPDATE_SWAGGER_FOLLOW';
export const UPDATE_TALENT_FOLLOW = 'UPDATE_TALENT_FOLLOW';

//Profile
export const SET_PROFILE_FEED = 'SET_PROFILE_FEED';
export const UPDATE_PROFILE_FEED = 'UPDATE_PROFILE_FEED';
export const UPDATE_PROFILE_FEED_COMMENT = 'UPDATE_PROFILE_FEED_COMMENT';
export const SET_PROFILE_DETAILS = 'SET_PROFILE_DETAILS';
export const SET_SUGGESTED_FRIENDS = 'SET_SUGGESTED_FRIENDS';
export const CLEAR_PROFILE_FEED = 'CLEAR_PROFILE_FEED';
export const CLEAR_PROFILE_DETAIL = 'CLEAR_PROFILE_DETAIL';
export const UPDATE_PROFILE_FEED_COMMENT_LIKE = 'UPDATE_PROFILE_FEED_COMMENT_LIKE';
export const UPDATE_PROFILE_FEED_COMMENT_REPLY = 'UPDATE_PROFILE_FEED_COMMENT_REPLY';
export const UPDATE_PROFILE_COMMENT_MANIPULATE = 'UPDATE_PROFILE_COMMENT_MANIPULATE';
export const UPDATE_PROFILE_FOLLOW = 'UPDATE_PROFILE_FOLLOW';

//Friends
export const SET_FRIENDS = 'SET_FRIENDS';
export const SET_FOLLOWINGS = 'SET_FOLLOWINGS';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';

//Common Feed
export const SET_MOST_POPULAR_FEED = 'SET_MOST_POPULAR_FEED';
export const CLEAR_MOST_POPULAR_FEED = 'CLEAR_MOST_POPULAR_FEED';
export const CLEAR_POST_DETAIL = 'CLEAR_POST_DETAIL';
export const SET_POST_DETAILS = 'SET_POST_DETAILS';
export const UPDATE_POST_DETAILS_TEXT = 'UPDATE_POST_DETAILS_TEXT';

//Settings
export const SET_SETTINGS_DATA = 'SET_SETTINGS_DATA';

//Market
export const SET_MARKET_FEED = 'SET_MARKET_FEED';
export const SET_MARKET_ITEM = 'SET_MARKET_ITEM';
export const RESET_MARKET_ITEM = 'RESET_MARKET_ITEM';

//Count
export const SET_COUNT = 'SET_COUNT';

//Messages
export const SET_MESSAGES_LIST = 'SET_MESSAGES_LIST';
export const SET_MESSAGES_DATA = 'SET_MESSAGES_DATA';
export const RESET_MESSAGES_DATA = 'RESET_MESSAGES_DATA';

//Find Friends
export const SET_FIND_FRIENDS = 'SET_FIND_FRIENDS';
export const RESET_FIND_FRIENDS = 'RESET_FIND_FRIENDS';

//Find Groups
export const SET_FIND_GROUPS = 'SET_FIND_GROUPS';
export const RESET_FIND_GROUPS = 'RESET_FIND_GROUPS';

//Group
export const SET_OWN_GROUPS = 'SET_OWN_GROUPS';
export const SET_OTHER_GROUPS = 'SET_OTHER_GROUPS';
export const SET_GROUP_INVITATIONS = 'SET_GROUP_INVITATIONS';
export const SET_GROUP_FEED = 'SET_GROUP_FEED';
export const UPDATE_GROUP_FEED = 'UPDATE_GROUP_FEED';
export const CLEAR_GROUP_FEED = 'CLEAR_GROUP_FEED';
export const CLEAR_GROUP_DETAILS = 'CLEAR_GROUP_DETAILS';
export const UPDATE_GROUP_FEED_COMMENT = 'UPDATE_GROUP_FEED_COMMENT';
export const UPDATE_GROUP_FEED_TEXT = 'UPDATE_GROUP_FEED_TEXT';
export const UPDATE_GROUP_FEED_DELETE = 'UPDATE_GROUP_FEED_DELETE';
export const RESET_GROUP_FEED = 'RESET_GROUP_FEED';
export const SET_GROUP_DETAILS = 'SET_GROUP_DETAILS';
export const SET_INVITATION_LIST = 'SET_INVITATION_LIST';
export const UPDATE_GROUP_FEED_COMMENT_LIKE = 'UPDATE_GROUP_FEED_COMMENT_LIKE';
export const UPDATE_GROUP_FEED_COMMENT_REPLY = 'UPDATE_GROUP_FEED_COMMENT_REPLY';
export const UPDATE_GROUP_COMMENT_MANIPULATE = 'UPDATE_GROUP_COMMENT_MANIPULATE';
export const SET_GROUP_ID = 'SET_GROUP_ID';
export const REMOVE_GROUP_ID = 'REMOVE_GROUP_ID';
export const UPDATE_GROUP_FOLLOW = 'UPDATE_GROUP_FOLLOW';

//Advertisements
export const SET_ADS = 'SET_ADS';

//HashTags
export const SET_HASHTAG_LIST = 'SET_HASHTAG_LIST';
export const UPDATE_HASHTAG_LIST = 'UPDATE_HASHTAG_LIST';
export const RESET_HASHTAG_LIST = 'RESET_HASHTAG_LIST';
export const SET_SUGGESTED_HASHTAGS = 'SET_SUGGESTED_HASHTAGS';
export const RESET_SUGGESTED_HASHTAGS = 'RESET_SUGGESTED_HASHTAGS';
export const SET_HASHTAG_DETAILS = 'SET_HASHTAG_DETAILS';
export const RESET_HASHTAG_DETAILS = 'RESET_HASHTAG_DETAILS';
export const FOLLOW_START_LOADING = 'FOLLOW_START_LOADING';
export const FOLLOW_STOP_LOADING = 'FOLLOW_STOP_LOADING';
export const UPDATE_HASHTAG_FOLLOW = 'UPDATE_HASHTAG_FOLLOW';

//Explore
export const SET_ENTERTAINMENT_LIST = 'SET_ENTERTAINMENT_LIST';
export const RESET_ENTERTAINMENT_LIST = 'RESET_ENTERTAINMENT_LIST';
export const ENTERTAINMENT_LOADING_START = 'ENTERTAINMENT_LOADING_START';
export const ENTERTAINMENT_LOADING_END = 'ENTERTAINMENT_LOADING_END';
